# -*- coding: utf-8 -*-
"""Apresentacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXCbyVKVm3EKv1lNmWKLx0vKL76QSrRe

# **imports**
"""

import pandas as pd

"""# **Importando os dados**

[Git das bases de dados](https://github.com/CSSEGISandData/COVID-19)
"""

df_mortes = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
df_curados = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

df_mortes

df_curados.head()

df_mortes.info()

"""# **Tirados as colunas Lat e Long**"""

df_mortes = df_mortes.drop(columns=["Lat", "Long"], axis=1)
df_curados = df_curados.drop(columns=["Lat", "Long"], axis=1)

df_curados.head()

"""# **Reatirando colunas sem dados**"""

df_mortes = df_mortes.dropna(subset=["Country/Region"])
df_curados = df_curados.dropna(subset=["Country/Region"])

df_curados.to_excel("teste.xlsx")

"""# **Somando os Country/Region**"""

df_mortes_sum = df_mortes.groupby("Country/Region").sum()
df_curados_sum = df_curados.groupby("Country/Region").sum()

df_curados_sum

"""Pegando o ultimo dia da banco de mortes"""

df_mortes_ultimo_dia = df_mortes.groupby("Country/Region").sum()

df_mortes_ultimo_dia =  df_mortes_ultimo_dia.iloc[:,-1]

df_mortes_ultimo_dia.describe()

df_mortes_ultimo_dia.max()

df_mortes_ultimo_dia_maximo_paises = df_mortes_ultimo_dia.index
df_mortes_ultimo_dia_maximo_mortes = df_mortes_ultimo_dia.values

"""Pegando o ultimo dia da banco de curados

"""

df_curados_ultimo_dia = df_curados_sum.iloc[:,-1]

df_curados_ultimo_dia_maximo_paises =  df_curados_ultimo_dia.index
df_curados_ultimo_dia_maximo_curados = df_curados_ultimo_dia.values

df_curados_ultimo_dia_maximo_curados

"""# **Pegandos dados do brasil**"""

df_mortes_sum_Brazil = df_mortes_sum.loc['Brazil']
df_curados_sum_Brazil = df_curados_sum.loc['Brazil']

df_mortes_sum_Brazil.head()

df_mortes_sum_Brazil.describe()

"""# **Pegando as datas e casos**"""

datas_mortes_brasil = df_mortes_sum_Brazil.index
casos_mortes_brasil = df_mortes_sum_Brazil.values

datas_curados_brasil = df_curados_sum_Brazil.index
casos_curados_brasil = df_curados_sum_Brazil.values

datas_mortes_brasil

datas_curados_brasil

casos_curados_brasil

casos_mortes_brasil

"""# **Retirando os dados com 0**"""

df_mortes_sum_Brazil = df_mortes_sum_Brazil[df_mortes_sum_Brazil > 0]
df_curados_sum_Brazil = df_curados_sum_Brazil[df_curados_sum_Brazil > 0]

df_mortes_sum_Brazil.describe()

df_mortes_sum_Brazil

df_curados_sum_Brazil

"""# **Atribuindo os novos valores das datas e casos > 0**"""

datas_mortes_brasil = df_mortes_sum_Brazil.index
casos_mortes_brasil = df_mortes_sum_Brazil.values

datas_curados_brasil = df_curados_sum_Brazil.index
casos_curados_brasil = df_curados_sum_Brazil.values

casos_curados_brasil

datas_curados_brasil

"""# **Delimitando o tamnho dos dados em 30 dias**"""

tam = len(df_mortes_sum_Brazil)
datas_curados_brasil_30_dias = datas_curados_brasil[tam-30:tam]
casos_curados_brasil_30_dias = casos_curados_brasil[tam-30:tam]

tam = len(df_curados_sum_Brazil)
datas_mortes_brasil_30_dias = datas_mortes_brasil[tam-30:tam]
casos_mortes_brasil_30_dias = casos_mortes_brasil[tam-30:tam]

casos_mortes_brasil_30_dias

casos_curados_brasil_30_dias

datas_curados_brasil_30_dias

"""# **Importando o matplot para a criação de gráficos**"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

!pip install seaborn

import seaborn as sns

plt.figure(figsize=(25,5))
plt.xticks(rotation=90)
plt.title("Total de mortes por COVID no Brasil - Periodo 16/03/2020 a 15/06/2021")
plt.bar(datas_mortes_brasil, casos_mortes_brasil)

plt.figure(figsize=(25,5))
plt.xticks(rotation=90)
plt.title("Total de mortes por COVID no Brasil - Periodo 16/03/2020 a 13/06/2021")
plt.plot(datas_mortes_brasil, casos_mortes_brasil)

plt.figure(figsize=(25,5))
plt.xticks(rotation=60)
plt.title("Total de mortes por COVID no Brasil- Periodo 17/05 a 15/06 de 2021")
plt.stem(datas_mortes_brasil_30_dias, casos_mortes_brasil_30_dias)

plt.figure(figsize=(25,5))
plt.xticks(rotation=60)
plt.title("Total de curados do COVID no Brasil- Periodo 15/05 a 16/06 de 2021")
plt.plot(datas_curados_brasil_30_dias, casos_curados_brasil_30_dias)

df_mortes_ultimo_dia_maximo_paises

plt.figure(figsize=(25,7))
plt.xticks(rotation=90)
plt.title("Distribuição da quantidade de mortos por COVID nos países - Até 15/06/2021")
plt.stem(df_mortes_ultimo_dia_maximo_paises, df_mortes_ultimo_dia_maximo_mortes)

plt.figure(figsize=(25,5))
plt.xticks(rotation=90)
plt.title("Total de curados do COVID nos países - Até 15/06/2021")
plt.bar(df_curados_ultimo_dia_maximo_paises, df_curados_ultimo_dia_maximo_curados)